df=read.csv("D:\\Cse-DS_Avijoy_Hazra_052\\CardioGoodFitness (1).csv")
print(df)
library(dplyr)

df_new<-df%>%slice_head(n=5)
print(df_new)
df_mean<-mean(df$Age)
print(paste("The mean age of the customers is :",df_mean))
df_median<-median(df$Age)
print(paste("The median age of the customers is :",df_median))
df_mode<-tabulate(factor(df$Age))
df_newmode<-table(df$Age)
max(df_newmode)
print(df_newmode)
print(df_mode)
max(paste("The mode age of the customer is:",max(df_mode)))
print(paste("The total sample is:",nrow(df)))
print(sum(count.fields(file.choose())))
print(paste("The correlation between fitness and age is:",cor(df$Fitness,df$Age)))
print(paste("The correlation between Miles and age is:",cor(df$Miles,df$Age)))
print(paste("The correlation between Fitness and Miles is:",cor(df$Miles,df$Fitness)))
