library(openxlsx)
df=read.xlsx("D:\\Cse-DS_Avijoy_Hazra_052\\Employees (1).xlsx")
print(df)
print(paste(nrow(df),"X",ncol(df)))
print(dim(df))
library(dplyr)
a<-df%>%arrange(desc(First.name))%>%filter(First.name=='Abbot')
print(a["Email"])
b<-df%>%count(Gender)
print(b)